server:
  port: 8081

spring:
  application:
    name: order-service
  reactor:
    context-propagation: auto

management:
  tracing:
    sampling:
      probability: 1.0

logstash:
  destination: ${LOGSTASH_DESTINATION:localhost:5000}

services:
  inventory:
    url: ${INVENTORY_URL:http://localhost:8082}
  payment:
    url: ${PAYMENT_URL:http://localhost:8083}
